repadmin /regkey xp-s-eur0555.europe.abb.com -strict
repadmin /regkey xe-s-eur0003.europe.abb.com -strict
repadmin /regkey XE-S-EUR0001.europe.abb.com -strict
repadmin /regkey IT-S-EUR0223.europe.abb.com -strict
repadmin /regkey IT-S-EUR0007.europe.abb.com -strict
repadmin /regkey it-s-eur0080.europe.abb.com -strict
repadmin /regkey XE-S-EUR0002.europe.abb.com -strict
repadmin /regkey XP-S-EUR0666.europe.abb.com -strict
repadmin /regkey xf-s-eur0004.europe.abb.com -strict
repadmin /regkey SA-S-EUR0213.europe.abb.com -strict
repadmin /regkey XQ-S-EUR0777.europe.abb.com -strict
repadmin /regkey XB-S-EUR0777.europe.abb.com -strict
repadmin /regkey TR-S-EUR0221.europe.abb.com -strict
repadmin /regkey xp-s-eur0555.europe.abb.com -strict
repadmin /regkey de-s-eur0220.europe.abb.com -strict
repadmin /regkey xf-s-eur0209.europe.abb.com -strict
repadmin /regkey XF-S-EUR0210.europe.abb.com -strict
repadmin /regkey pl-s-eur0217.europe.abb.com -strict
repadmin /regkey ae-s-eur0177.europe.abb.com -strict
repadmin /regkey eg-s-eur0202.europe.abb.com -strict
repadmin /regkey za-s-eur0211.europe.abb.com -strict
repadmin /regkey xe-s-eur0010.europe.abb.com -strict
repadmin /regkey XE-S-EUR0197.europe.abb.com -strict
repadmin /regkey XF-S-EUR0224.europe.abb.com -strict
repadmin /regkey XA-S-EUR0666.europe.abb.com -strict
repadmin /regkey DE-S-EUR0218.europe.abb.com -strict
repadmin /regkey xe-s-eur0208.europe.abb.com -strict
repadmin /regkey DE-S-EUR0219.europe.abb.com -strict
repadmin /regkey KZ-S-EUR0222.europe.abb.com -strict
repadmin /regkey XE-S-EUR0207.europe.abb.com -strict
repadmin /regkey XA-S-EUR0555.europe.abb.com -strict
repadmin /regkey CZ-S-EUR0212.europe.abb.com -strict




repadmin /regkey XP-S-ABB0032.abb.com -strict
repadmin /regkey XP-S-ABB0033.abb.com -strict
repadmin /regkey XA-S-ABB0021.abb.com -strict
repadmin /regkey XA-S-ABB0022.abb.com -strict
repadmin /regkey xp-s-abb0031.abb.com -strict
repadmin /regkey XF-S-ABB0013.abb.com -strict
repadmin /regkey xq-s-abb0033.abb.com -strict
repadmin /regkey xb-s-abb0023.abb.com -strict
repadmin /regkey XE-S-ABB0011.abb.com -strict
repadmin /regkey XE-S-ABB0012.abb.com -strict

repadmin /regkey US-S-AME0196.AMERICAS.ABB.COM -strict
repadmin /regkey XF-S-AME0777.americas.abb.com -strict
repadmin /regkey XP-S-AME0666.americas.abb.com -strict
repadmin /regkey XQ-S-AME0777.americas.abb.com -strict
repadmin /regkey XE-S-AME0666.americas.abb.com -strict
repadmin /regkey BR-S-AME0197.americas.abb.com -strict
repadmin /regkey XA-S-AME0183.americas.abb.com -strict
repadmin /regkey XB-S-AME0186.americas.abb.com -strict
repadmin /regkey XB-S-AME0004.americas.abb.com -strict
repadmin /regkey XB-S-AME0185.americas.abb.com -strict
repadmin /regkey ca-s-ame0177.americas.abb.com -strict
repadmin /regkey xp-s-ame0555.americas.abb.com -strict
repadmin /regkey XA-S-AME0002.americas.abb.com -strict
repadmin /regkey XE-S-AME0555.americas.abb.com -strict
repadmin /regkey CL-S-AME0194.americas.abb.com -strict
repadmin /regkey XA-S-AME0184.americas.abb.com -strict
repadmin /regkey XA-S-AME0009.americas.abb.com -strict
repadmin /regkey US-S-AME0193.americas.abb.com -strict
repadmin /regkey XA-S-AME0001.americas.abb.com -strict
repadmin /regkey US-S-AME0180.americas.abb.com -strict
repadmin /regkey US-S-AME0182.americas.abb.com -strict
repadmin /regkey XA-S-AME0003.americas.abb.com -strict

repadmin /regkey XP-S-APC0001.asiapacific.abb.com -strict
repadmin /regkey XB-S-APC0777.asiapacific.abb.com -strict
repadmin /regkey XP-S-APC0083.asiapacific.abb.com -strict
repadmin /regkey XP-S-APC0002.asiapacific.abb.com -strict
repadmin /regkey XF-S-APC0777.asiapacific.abb.com -strict
repadmin /regkey xa-s-apc0666.asiapacific.abb.com -strict
repadmin /regkey JP-S-APC0095.asiapacific.abb.com -strict
repadmin /regkey XE-S-APC0666.asiapacific.abb.com -strict
repadmin /regkey XQ-S-APC0004.asiapacific.abb.com -strict
repadmin /regkey XQ-S-APC0085.asiapacific.abb.com -strict
repadmin /regkey AU-S-APC0088.asiapacific.abb.com -strict
repadmin /regkey XP-S-APC0084.asiapacific.abb.com -strict
repadmin /regkey IN-S-APC0039.asiapacific.abb.com -strict
repadmin /regkey XP-S-APC0009.asiapacific.abb.com -strict
repadmin /regkey CN-S-APC0093.asiapacific.abb.com -strict
repadmin /regkey in-s-apc0038.asiapacific.abb.com -strict
repadmin /regkey XP-S-APC0003.asiapacific.abb.com -strict
repadmin /regkey XP-S-APC0010.asiapacific.abb.com -strict
repadmin /regkey XE-S-APC0555.asiapacific.abb.com -strict
repadmin /regkey XQ-S-APC0086.asiapacific.abb.com -strict
repadmin /regkey cn-s-apc0092.asiapacific.abb.com -strict
repadmin /regkey XA-S-APC0555.asiapacific.abb.com -strict



repadmin /regkey xp-s-nme0555.nmea.abb.com -strict
repadmin /regkey xe-s-nme0010.nmea.abb.com -strict
repadmin /regkey xf-s-nme0089.nmea.abb.com -strict
repadmin /regkey XP-S-NME0666.nmea.abb.com -strict
repadmin /regkey XE-S-NME0002.nmea.abb.com -strict
repadmin /regkey XE-S-NME0086.nmea.abb.com -strict
repadmin /regkey XF-S-NME0088.nmea.abb.com -strict
repadmin /regkey xa-s-nme0666.nmea.abb.com -strict
repadmin /regkey no-s-nme0095.nmea.abb.com -strict
repadmin /regkey XQ-S-NME0777.nmea.abb.com -strict
repadmin /regkey SE-S-NME0090.nmea.abb.com -strict
repadmin /regkey XE-S-NME0087.nmea.abb.com -strict
repadmin /regkey fi-s-nme0093.nmea.abb.com -strict
repadmin /regkey XE-S-NME0001.nmea.abb.com -strict
repadmin /regkey FI-S-NME0092.nmea.abb.com -strict
repadmin /regkey XB-S-NME0777.nmea.abb.com -strict
repadmin /regkey SE-S-NME0091.nmea.abb.com -strict
repadmin /regkey XA-S-NME0555.nmea.abb.com -strict
repadmin /regkey XF-S-NME0004.nmea.abb.com -strict
repadmin /regkey XE-S-NME0003.nmea.abb.com -strict