

#Get-ADReplicationPartnerMetadata -Target AD1 -Partition Schema | Format-Table
#Get-ADReplicationPartnerMetadata -Target AD1 -
#Get-ADReplicationFailure -Target AD1 | Select-Object Server, Partner, FirstFailureTime, FailureCount, FailureType
#Get-ADReplicationConnection -Properties * -Filter "*" | Select-Object Name, AutoGenerated, InterSiteTransportProtocol, schedule, fromServer | Format-Table


function Test-WinADObjectReplication {
    [CmdletBinding()]
    param(
        $Object,
        [switch] $IncludeDeletedObjects,
        [switch] $ShowAllLinkedValues,
        [string] $Server
    )

    $ObjectInformation = Get-WinADObject -Identity $Object


    $getADReplicationAttributeMetadataSplat = @{
        Object                = $ObjectInformation.DistinguishedName
        IncludeDeletedObjects = $IncludeDeletedObjects.IsPresent
        ShowAllLinkedValues   = $ShowAllLinkedValues.IsPresent
        Server                = $Server
    }

    $Values = Get-ADReplicationAttributeMetadata @getADReplicationAttributeMetadataSplat
    $Values

}

Test-WinADObjectReplication -Object 'teeest' -Server 'AD1' | Format-Table

#repadmin.exe /replsingleobj 'AD1' 'AD2' 'CN=TEEEST,OU=Defender2016,OU=Servers,OU=Devices,OU=Production,DC=ad,DC=evotec,DC=xyz'